# 03. Data Preprocessing | المعالجة المسبقة للبيانات

## 📚 Prerequisites (What You Need First) | المتطلبات الأساسية

**BEFORE starting this notebook**, you should have completed:
- ✅ **Example 1: Data Loading and Exploration** - Know your data structure
- ✅ **Example 2: Data Cleaning** - Have clean data to preprocess
- ✅ **Basic ML concepts**: Features, targets, training vs testing

**If you haven't completed these**, you might struggle with:
- Understanding why preprocessing is needed
- Knowing which preprocessing method to use
- Understanding the difference between scaling methods

---

## 🔗 Where This Notebook Fits | مكان هذا الدفتر

**This is the THIRD example** - it prepares clean data for machine learning!

**Why this example THIRD?**
- **Before** you can build ML models, you need preprocessed data
- **Before** you can train models, you need scaled features
- **Before** you can make predictions, you need encoded categories

**Builds on**: 
- 📓 Example 1: Data Loading (we know our data)
- 📓 Example 2: Data Cleaning (we have clean data)

**Leads to**: 
- 📓 Example 4: Linear Regression (needs preprocessed data)
- 📓 Example 5: Polynomial Regression (needs scaled features)
- 📓 All ML models (all need preprocessing!)

**Why this order?**
1. Preprocessing transforms **clean data into ML-ready format**
2. Preprocessing teaches you **scaling vs encoding** (different problems, different solutions)
3. Preprocessing shows you **train-test split** (essential for evaluation)

---

## The Story: Preparing Ingredients for Cooking | القصة: تحضير المكونات للطبخ

Imagine you're cooking. **Before** you can cook, you need to prepare ingredients - cut vegetables to the same size, marinate meat, measure spices. **After** preparing everything uniformly, you can cook a perfect meal!

Same with machine learning: **Before** building models, we preprocess data - scale features to same range, encode categories to numbers, split into train/test. **After** preprocessing, we can build accurate models!

---

## Why Data Preprocessing Matters | لماذا تهم المعالجة المسبقة للبيانات؟

Preprocessing is essential for ML success:
- **Feature Scaling**: Algorithms work better when features are on similar scales
- **Encoding**: ML algorithms need numbers, not text categories
- **Train-Test Split**: We need separate data to evaluate model performance
- **Without Preprocessing**: Models fail or perform poorly

## Learning Objectives | أهداف التعلم
1. Scale features using Standardization and Normalization
2. Encode categorical variables (Label vs One-Hot)
3. Split data into training and testing sets
4. Understand when to use each preprocessing method
5. Build a complete preprocessing pipeline

In [1]:
# Step 1: Import necessary libraries
# These libraries help us preprocess data for machine learning

import pandas as pd  # For data manipulation
import numpy as np   # For numerical operations
from sklearn.preprocessing import (
    StandardScaler,    # For standardization (mean=0, std=1)
    MinMaxScaler,      # For normalization (range 0-1)
    LabelEncoder,      # For ordinal encoding
    OneHotEncoder      # For nominal encoding
)
from sklearn.model_selection import train_test_split  # For splitting data

print("✅ Libraries imported successfully!")
print("\n📚 What each preprocessing tool does:")
print("   - StandardScaler: Scale features to mean=0, std=1 (z-score)")
print("   - MinMaxScaler: Scale features to range [0, 1]")
print("   - LabelEncoder: Convert categories to numbers (ordinal)")
print("   - OneHotEncoder: Convert categories to binary columns (nominal)")
print("   - train_test_split: Split data into train/test sets")

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


✅ Libraries imported successfully!

📚 What each preprocessing tool does:
   - StandardScaler: Scale features to mean=0, std=1 (z-score)
   - MinMaxScaler: Scale features to range [0, 1]
   - LabelEncoder: Convert categories to numbers (ordinal)
   - OneHotEncoder: Convert categories to binary columns (nominal)
   - train_test_split: Split data into train/test sets


## Part 1: Setting the Scene | الجزء الأول: إعداد المشهد

**BEFORE**: We have clean data, but it's not ready for machine learning - features have different scales, categories are text, and we haven't split the data.

**AFTER**: We'll preprocess the data - scale features, encode categories, split into train/test - making it ready for ML models!

**Why this matters**: Most ML algorithms require preprocessed data. Without it, models fail or give poor results!

In [2]:
# Create sample data with different scales and categories
# This simulates real-world data that needs preprocessing

print("\n1. Creating sample data...")
print("إنشاء بيانات نموذجية...")

np.random.seed(42)  # For reproducibility
data = {
    'age': np.random.randint(20, 60, 100),              # Range: 20-60
    'salary': np.random.randint(30000, 100000, 100),    # Range: 30k-100k (different scale!)
    'experience': np.random.uniform(0, 15, 100),        # Range: 0-15 (different scale!)
    'city': np.random.choice(['Riyadh', 'Jeddah', 'Dammam', 'Khobar'], 100),  # Categorical (text)
    'education': np.random.choice(['Bachelor', 'Master', 'PhD'], 100),        # Categorical (text)
    'target': np.random.choice([0, 1], 100)  # Binary target for classification
}
# pd.DataFrame(data)
# - pd.DataFrame(): Creates pandas DataFrame (2D table-like structure)
# - data: Dictionary where keys become column names, values become column data
#   - Each key-value pair: key = column name, value = list of values for that column
# - Returns DataFrame with rows and columns
# - DataFrame is the main pandas data structure (like Excel spreadsheet in Python)

df = pd.DataFrame(data)

print("\n📊 Original Data:")
print(df.head())
print(f"\n📐 Data Shape: {df.shape}")
print("\n🔍 Notice:")
print("   - Numeric features have VERY different scales (age: 20-60, salary: 30k-100k)")
print("   - Categorical features are text (city, education)")
print("   - ML algorithms need same-scale numbers!")



1. Creating sample data...
إنشاء بيانات نموذجية...

📊 Original Data:
   age  salary  experience    city education  target
0   58   65222    9.899761  Jeddah  Bachelor       0
1   48   93335   12.258333  Dammam    Master       0
2   34   40965    8.328012  Riyadh    Master       0
3   27   54538    7.944759  Jeddah    Master       0
4   40   38110    3.627784  Dammam  Bachelor       1

📐 Data Shape: (100, 6)

🔍 Notice:
   - Numeric features have VERY different scales (age: 20-60, salary: 30k-100k)
   - Categorical features are text (city, education)
   - ML algorithms need same-scale numbers!


## Step 1: Create Sample Data | الخطوة 1: إنشاء بيانات نموذجية

**BEFORE**: We need to learn preprocessing, but we need sample data with different scales and categories.

**AFTER**: We'll create data with numeric features (different scales) and categorical features (text) to practice preprocessing!

**Why create this data?** Real datasets have these characteristics - we need to learn how to handle them.

In [3]:
print("\n" + "=" * 60)
print("2. Feature Scaling - Standardization")
print("قياس الميزات - التوحيد المعياري")
print("=" * 60)



2. Feature Scaling - Standardization
قياس الميزات - التوحيد المعياري


## Step 2: Feature Scaling - Standardization | الخطوة 2: قياس الميزات - التوحيد المعياري

**BEFORE**: Features have very different scales (age: 20-60, salary: 30k-100k). Algorithms will be biased toward larger numbers!

**AFTER**: We'll standardize features so they all have mean=0 and std=1, putting them on the same scale!

**Why Standardization?**
- Formula: `(x - mean) / std`
- Result: Mean = 0, Standard Deviation = 1
- Use when: Data is normally distributed, outliers are important
- Good for: Linear models, neural networks, distance-based algorithms

**Note**: Remove problematic outliers first (Example 2), then standardize. Standardization preserves outliers, so clean data first!

In [4]:
# Create StandardScaler object
# Standardization formula: (x - mean) / std
# This transforms data so mean=0 and std=1

# StandardScaler()
# - Creates scaler object for standardization
# - Standardization: (x - mean) / std
#   - Transforms data so mean = 0, standard deviation = 1
#   - Centers data around 0, scales to unit variance
# - Two-step process:
#   1. .fit(): Learn mean and std from data
#   2. .transform(): Apply transformation
# .fit_transform(data)
# - Two operations in one: .fit() then .transform()
#   1. .fit(): Learns parameters from data (mean/std, categories, etc.)
#   2. .transform(): Applies transformation using learned parameters
# - Use on training data
# - For test data, use only .transform() (don't refit!)

# - Or use .fit_transform(): Do both in one step
# - Important: Fit on training data, transform both train and test
scaler_standard = StandardScaler()
print("   ✅ StandardScaler created")
print("   Formula: (x - mean) / std")

   ✅ StandardScaler created
   Formula: (x - mean) / std


In [5]:
# Select numeric columns for scaling
# Why only numeric? Categorical columns need encoding, not scaling!
numeric_cols = ['age', 'salary', 'experience']
df_scaled_standard = df.copy()
print(f"   Scaling columns: {numeric_cols}")

   Scaling columns: ['age', 'salary', 'experience']


In [ ]:
# Fit and transform the data
# .fit_transform() learns the mean/std from data, then transforms it
# Why fit_transform? We learn parameters from training data, then apply to all data

# scaler_standard.fit_transform(df[numeric_cols])
# - .fit_transform(): Two operations in one
#   1. .fit(): Learns mean and std from data
#      - Calculates mean and std for each column
#      - Stores these values in scaler object
#   2. .transform(): Applies standardization using learned parameters
#      - Formula: (x - learned_mean) / learned_std
#      - Transforms each value in column
# - df[numeric_cols]: Selects only numeric columns to scale
#   - List of column names: ['age', 'salary', 'experience']
#   - Returns DataFrame with only those columns
# - Result: All numeric columns now have mean≈0 and std≈1
# - Note: In real ML, fit on training data, transform on both train and test
df_scaled_standard[numeric_cols] = scaler_standard.fit_transform(df[numeric_cols])

print("\n✅ After Standardization (mean=0, std=1):")
print("بعد التوحيد المعياري (متوسط=0، انحراف معياري=1):")
print(f"   Age - Mean: {df_scaled_standard['age'].mean():.4f}, Std: {df_scaled_standard['age'].std():.4f}")
print(f"   Salary - Mean: {df_scaled_standard['salary'].mean():.4f}, Std: {df_scaled_standard['salary'].std():.4f}")
print(f"   Experience - Mean: {df_scaled_standard['experience'].mean():.4f}, Std: {df_scaled_standard['experience'].std():.4f}")
print("\n   ✅ All features now have mean≈0 and std≈1!")
print("\n📄 Scaled data (first 5 rows):")
print("   (Values like 1.67 = 1.67 standard deviations above mean, -1.36 = below mean)")
print(df_scaled_standard[numeric_cols].head())


✅ After Standardization (mean=0, std=1):
بعد التوحيد المعياري (متوسط=0، انحراف معياري=1):
   Age - Mean: 0.0000, Std: 1.0050
   Salary - Mean: 0.0000, Std: 1.0050
   Experience - Mean: 0.0000, Std: 1.0050

   ✅ All features now have mean≈0 and std≈1!

   📝 Note: Values like 1.67, -1.36 are normal for standardized data!
   📝 They represent how many standard deviations away from the mean
   📝 (e.g., 1.67 means 1.67 standard deviations above the mean)

📄 Scaled data (first 5 rows):
        age    salary  experience
0  1.670713 -0.057025    0.366648
1  0.801003  1.290892    0.918449
2 -0.416591 -1.220060   -0.001071
3 -1.025388 -0.569284   -0.090735
4  0.105235 -1.356947   -1.100715


## Step 3: Feature Scaling - Normalization (Min-Max) | الخطوة 3: قياس الميزات - التطبيع

**BEFORE**: Features have different ranges. We want them all in the same range [0, 1].

**AFTER**: We'll normalize features so they all range from 0 to 1!

**Why Normalization (Min-Max)?**
- Formula: `(x - min) / (max - min)`
- Result: Range [0, 1]
- Use when: Data is not normally distributed, you want bounded values
- Good for: Neural networks, algorithms that need [0,1] range

In [7]:
# Normalization: (x - min) / (max - min) -> range [0, 1]
# التطبيع: (x - الأدنى) / (الأعلى - الأدنى) -> النطاق [0, 1]

# MinMaxScaler()
# - Creates scaler object for min-max normalization
# - Normalization: (x - min) / (max - min)
#   - Transforms data to range [0, 1]
#   - Minimum value becomes 0, maximum becomes 1
# - Two-step process:
#   1. .fit(): Learn min and max from data
#   2. .transform(): Apply transformation
# - Or use .fit_transform(): Do both in one step
# - Use when: Data not normally distributed, need bounded [0,1] range
scaler_minmax = MinMaxScaler()
df_scaled_minmax = df.copy()
df_scaled_minmax[numeric_cols] = scaler_minmax.fit_transform(df[numeric_cols])
print("\nAfter Min-Max Normalization (range 0-1):")
print("بعد التطبيع بالأدنى-الأعلى (النطاق 0-1):")
print(f"Age - Min: {df_scaled_minmax['age'].min():.4f}, Max: {df_scaled_minmax['age'].max():.4f}")
print(f"Salary - Min: {df_scaled_minmax['salary'].min():.4f}, Max: {df_scaled_minmax['salary'].max():.4f}")
print(df_scaled_minmax[numeric_cols].head())


After Min-Max Normalization (range 0-1):
بعد التطبيع بالأدنى-الأعلى (النطاق 0-1):
Age - Min: 0.0000, Max: 1.0000
Salary - Min: 0.0000, Max: 1.0000
        age    salary  experience
0  0.974359  0.507795    0.664901
1  0.717949  0.915484    0.824535
2  0.358974  0.156025    0.558521
3  0.179487  0.352858    0.532582
4  0.512821  0.114622    0.240399


In [8]:
# 4. Label Encoding (for ordinal categories)
# الترميز بالعلامات (للفئات الترتيبية)
print("\n" + "=" * 60)
print("4. Label Encoding")
print("الترميز بالعلامات")
print("=" * 60)

# LabelEncoder()
# - Creates encoder for ordinal categorical data
# - Ordinal: Categories have order (e.g., Bachelor < Master < PhD)
# - Converts text categories to integers (0, 1, 2, ...)
# - Two-step process:
#   1. .fit(): Learn unique categories
#   2. .transform(): Convert categories to numbers
# - Or use .fit_transform(): Do both in one step
# - Use when: Categories have meaningful order
label_encoder = LabelEncoder()


4. Label Encoding
الترميز بالعلامات


In [9]:
# Encode education (if we assume ordinal: Bachelor < Master < PhD)
df_encoded = df.copy()

# label_encoder.fit_transform(df['education'])
# - .fit_transform(): Two operations in one
#   1. .fit(): Learns unique categories from data
#      - Finds all unique values (e.g., 'Bachelor', 'Master', 'PhD')
#      - Assigns numbers in alphabetical order (or order found)
#   2. .transform(): Converts categories to integers
#      - 'Bachelor' → 0, 'Master' → 1, 'PhD' → 2
# - df['education']: Passes education column as Series
# - Returns numpy array with encoded integers
# - label_encoder.classes_: Shows mapping (original categories)
df_encoded['education_encoded'] = label_encoder.fit_transform(df['education'])

# label_encoder.classes_
# - Returns array of unique categories in order they were encoded
# - Used to see mapping: classes_[0] = first category, etc.
print("\nLabel Encoding for Education:")
print("الترميز بالعلامات للتعليم:")
print("Mapping / التعيين:")
for i, label in enumerate(label_encoder.classes_):
    print(f"  {label}: {i}")
print("\nEncoded values:")
print(df_encoded[['education', 'education_encoded']].head(10))


Label Encoding for Education:
الترميز بالعلامات للتعليم:
Mapping / التعيين:
  Bachelor: 0
  Master: 1
  PhD: 2

Encoded values:
  education  education_encoded
0  Bachelor                  0
1    Master                  1
2    Master                  1
3    Master                  1
4  Bachelor                  0
5    Master                  1
6    Master                  1
7  Bachelor                  0
8       PhD                  2
9  Bachelor                  0


In [10]:
# 5. One-Hot Encoding (for nominal categories)
# الترميز الواحد-الساخن (للفئات الاسمية)
print("\n" + "=" * 60)
print("5. One-Hot Encoding")
print("الترميز الواحد-الساخن")
print("=" * 60)


5. One-Hot Encoding
الترميز الواحد-الساخن


In [11]:
# Using pandas get_dummies (easier)
# استخدام pandas get_dummies (أسهل)

# pd.get_dummies(df, columns=['city', 'education'], prefix=['city', 'edu'])
# - pd.get_dummies(): Creates one-hot encoded columns for categorical data
# - df: DataFrame to encode
# - columns=['city', 'education']: Columns to encode (list of column names)
# - prefix=['city', 'edu']: Prefix for new column names
#   - 'city' column with values ['Riyadh', 'Jeddah'] → 'city_Riyadh', 'city_Jeddah'
#   - 'education' column → 'edu_Bachelor', 'edu_Master', 'edu_PhD'
# - One-hot encoding: Each category becomes a binary column (0 or 1)
#   - Example: If city='Riyadh', then city_Riyadh=1, others=0
# - Returns DataFrame with original columns + new binary columns
# - Use for: Nominal categories (no order, like city names)
df_onehot = pd.get_dummies(df, columns=['city', 'education'], prefix=['city', 'edu'])

# df_onehot.columns.tolist()
# - df_onehot.columns: Returns Index with column names
# - .tolist(): Converts to Python list
# - Shows all column names after encoding
print("\nOne-Hot Encoded columns:")
print("الأعمدة المشفرة بالواحد-الساخن:")
print(df_onehot.columns.tolist())
print("\nSample of One-Hot Encoded data:")
print(df_onehot[['age', 'salary'] + [col for col in df_onehot.columns if 'city_' in col or 'edu_' in col]].head())


One-Hot Encoded columns:
الأعمدة المشفرة بالواحد-الساخن:
['age', 'salary', 'experience', 'target', 'city_Dammam', 'city_Jeddah', 'city_Khobar', 'city_Riyadh', 'edu_Bachelor', 'edu_Master', 'edu_PhD']

Sample of One-Hot Encoded data:
   age  salary  city_Dammam  city_Jeddah  city_Khobar  city_Riyadh  \
0   58   65222        False         True        False        False   
1   48   93335         True        False        False        False   
2   34   40965        False        False        False         True   
3   27   54538        False         True        False        False   
4   40   38110         True        False        False        False   

   edu_Bachelor  edu_Master  edu_PhD  
0          True       False    False  
1         False        True    False  
2         False        True    False  
3         False        True    False  
4          True       False    False  


In [12]:
# Using sklearn OneHotEncoder (for more control)
# استخدام sklearn OneHotEncoder (لمزيد من التحكم)
print("\n--- Using sklearn OneHotEncoder ---")
onehot_encoder = OneHotEncoder(sparse_output=False, drop='first')

city_encoded = onehot_encoder.fit_transform(df[['city']])
print("City encoding classes:")
print(onehot_encoder.categories_)
print(f"\nEncoded shape: {city_encoded.shape}")
print("First 5 encoded values:")
print(city_encoded[:5])


--- Using sklearn OneHotEncoder ---
City encoding classes:
[array(['Dammam', 'Jeddah', 'Khobar', 'Riyadh'], dtype=object)]

Encoded shape: (100, 3)
First 5 encoded values:
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Method 2: Using sklearn OneHotEncoder (for more control)
# Why sklearn? More control - can drop first column to avoid multicollinearity
# drop='first' removes one column (redundant - can be inferred from others)

print("\n--- Using sklearn OneHotEncoder ---")

# OneHotEncoder(sparse_output=False, drop='first')
# - OneHotEncoder(): Creates one-hot encoder object
# - sparse_output=False: Returns dense array (True returns sparse matrix)
# - drop='first': Drops first category column to avoid multicollinearity
#   - If 4 cities, creates 3 columns (not 4)
#   - One column is redundant (can be inferred from others)
#   - Prevents perfect correlation between columns
onehot_encoder = OneHotEncoder(sparse_output=False, drop='first')

# onehot_encoder.fit_transform(df[['city']])
# - .fit_transform(): Learns categories and encodes
#   1. .fit(): Learns unique categories
#   2. .transform(): Creates binary columns
# - df[['city']]: Double brackets [[]] to pass as DataFrame (not Series)
#   - OneHotEncoder expects 2D input (DataFrame or 2D array)
# - Returns numpy array with binary columns
# - Example: 4 cities → 3 columns (if drop='first')
city_encoded = onehot_encoder.fit_transform(df[['city']])

print("   City encoding classes:")
print(f"   {onehot_encoder.categories_}")
print(f"\n   Encoded shape: {city_encoded.shape}")
print(f"   (4 cities → 3 columns, because drop='first' removes one)")
print("\n   First 5 encoded values:")
print(city_encoded[:5])
print("\n   ✅ Each row has 1 in one column (the city), 0 in others")



--- Using sklearn OneHotEncoder ---
   City encoding classes:
   [array(['Dammam', 'Jeddah', 'Khobar', 'Riyadh'], dtype=object)]

   Encoded shape: (100, 3)
   (4 cities → 3 columns, because drop='first' removes one)

   First 5 encoded values:
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]]

   ✅ Each row has 1 in one column (the city), 0 in others


## Step 6: Train-Test Split | الخطوة 6: تقسيم البيانات إلى تدريب واختبار

**BEFORE**: We have all our data together. We can't evaluate model performance on data it has seen!

**AFTER**: We'll split data into training (80%) and testing (20%) sets!

**Why Train-Test Split?**
- **Training set**: Used to train/learn the model
- **Test set**: Used to evaluate model performance (unseen data)
- **Why separate?** Testing on training data gives false high scores (overfitting)
- **Standard split**: 80% train, 20% test (can vary based on dataset size)

In [14]:
# Prepare features and target
X = df[['age', 'salary', 'experience']]
y = df['target']

In [15]:
# Split into train and test sets (80% train, 20% test)
# التقسيم إلى مجموعات تدريب واختبار (80% تدريب، 20% اختبار)

# train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
# - train_test_split(): Splits data into training and testing sets
# - X: Features (input variables) - DataFrame or array
# - y: Target (output variable) - Series or array
# - test_size=0.2: 20% for testing, 80% for training (can use 0.25 for 25%)
# - random_state=42: Seed for random number generator
#   - Ensures same split every time (reproducibility)
#   - Different seeds = different splits
# - stratify=y: Maintains class distribution in train/test
#   - If y has 60% class 0, 40% class 1, train/test will have same ratio
#   - Important for imbalanced datasets
# - Returns 4 arrays: X_train, X_test, y_train, y_test
#   - X_train: Training features (80% of X)
#   - X_test: Testing features (20% of X)
#   - y_train: Training targets (80% of y)
#   - y_test: Testing targets (20% of y)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y  # Maintain class distribution
)
print(f"\nOriginal data shape: {X.shape}")
print(f"شكل البيانات الأصلية: {X.shape}")
print(f"\nTraining set:")
print(f"مجموعة التدريب:")
print(f"  X_train: {X_train.shape}")
print(f"  y_train: {y_train.shape}")
print(f"\nTest set:")
print(f"مجموعة الاختبار:")
print(f"  X_test: {X_test.shape}")
print(f"  y_test: {y_test.shape}")
print(f"\nTrain percentage: {len(X_train) / len(X) * 100:.1f}%")
print(f"Test percentage: {len(X_test) / len(X) * 100:.1f}%")


Original data shape: (100, 3)
شكل البيانات الأصلية: (100, 3)

Training set:
مجموعة التدريب:
  X_train: (80, 3)
  y_train: (80,)

Test set:
مجموعة الاختبار:
  X_test: (20, 3)
  y_test: (20,)

Train percentage: 80.0%
Test percentage: 20.0%


## 7. Complete Preprocessing Pipeline Example

In [16]:
# مثال خط أنابيب المعالجة الكاملة
print("\n" + "=" * 60)
print("7. Complete Preprocessing Pipeline")
print("خط أنابيب المعالجة الكاملة")
print("=" * 60)

def preprocess_data(df, numeric_cols, categorical_cols, target_col, test_size=0.2):
    """
    Complete preprocessing pipeline
    خط أنابيب المعالجة الكاملة
    """
    # Separate features and target
    X = df[numeric_cols + categorical_cols].copy()
    y = df[target_col].copy()
    
    # One-hot encode categorical variables
    X_encoded = pd.get_dummies(X, columns=categorical_cols, drop_first=True)
    
    # Scale numeric features
    scaler = StandardScaler()
    X_encoded[numeric_cols] = scaler.fit_transform(X_encoded[numeric_cols])
    
    # Split data
# train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
# - Splits data into training and testing sets
# - X: Features (input variables), y: Target (output variable)
# - test_size=0.2: 20% for testing, 80% for training
# - random_state=42: Seed for reproducibility (same split every time)
# - stratify=y: Maintains class distribution in train/test (for classification)
# - Returns: X_train, X_test, y_train, y_test

    X_train, X_test, y_train, y_test = train_test_split(
        X_encoded, y, test_size=test_size, random_state=42, stratify=y
    )
    
    return X_train, X_test, y_train, y_test, scaler


7. Complete Preprocessing Pipeline
خط أنابيب المعالجة الكاملة


## Step 8: Decision Framework - When to Use Each Preprocessing Method | الخطوة 8: إطار القرار - متى تستخدم كل طريقة معالجة

**BEFORE**: You've learned different preprocessing methods, but when should you use each one?

**AFTER**: You'll have a clear decision framework to choose the right preprocessing method for any situation!

**Why this matters**: Using the wrong preprocessing method can:
- **Break your models** → Wrong scaling causes algorithm failures
- **Reduce performance** → Inappropriate encoding loses information
- **Waste time** → Trying all methods without guidance

---

### 🎯 Decision Framework for Feature Scaling | إطار القرار لقياس الميزات

**Key Question**: Should I use **STANDARDIZATION** or **NORMALIZATION**?

#### Decision Tree:

```
Do you have numeric features?
├─ NO → No scaling needed (categorical features need encoding, not scaling)
│
└─ YES → Are features on different scales?
    ├─ NO → No scaling needed (already on similar scales)
    │
    └─ YES → Is data normally distributed?
        ├─ YES → Use STANDARDIZATION (StandardScaler)
        │   └─ Why? Preserves distribution, handles outliers well
        │
        └─ NO → Do you need bounded values [0, 1]?
            ├─ YES → Use NORMALIZATION (MinMaxScaler)
            │   └─ Why? Neural networks, algorithms requiring [0,1] range
            │
            └─ NO → Use STANDARDIZATION (StandardScaler)
                └─ Why? More robust to outliers, preserves relationships
```

#### Comparison Table:

| Method | When to Use | Pros | Cons | Example |
|--------|-------------|------|------|---------|
| **Standardization** | Normal distribution, outliers present, linear models | • Preserves distribution<br>• Robust to outliers<br>• Mean=0, Std=1 | • Can produce values outside [0,1]<br>• Assumes normal distribution | Age (20-60), Salary (30k-100k) |
| **Normalization** | Non-normal distribution, neural networks, need [0,1] | • Bounded [0,1]<br>• Works with any distribution<br>• Good for neural networks | • Sensitive to outliers<br>• May compress data too much | Image pixels (0-255), Ratings (1-5) |
| **No Scaling** | Features already on similar scales, tree-based models | • No transformation needed<br>• Preserves original values | • Only works if scales are similar | All features 0-1, or all 100-200 |

---

### 🎯 Decision Framework for Categorical Encoding | إطار القرار لترميز البيانات الفئوية

**Key Question**: Should I use **LABEL ENCODING** or **ONE-HOT ENCODING**?

#### Decision Tree:

```
Do you have categorical features?
├─ NO → No encoding needed (all features are numeric)
│
└─ YES → Is there an inherent order (ordinal)?
    ├─ YES → Use LABEL ENCODING
    │   └─ Why? Preserves order (e.g., Low < Medium < High)
    │
    └─ NO → How many unique categories?
        ├─ < 10 → Use ONE-HOT ENCODING
        │   └─ Why? Creates separate columns, no false order
        │
        └─ ≥ 10 → Consider alternatives:
            ├─ Use ONE-HOT if important features
            │   └─ Why? Each category matters
            │
            └─ Use TARGET ENCODING or frequency encoding
                └─ Why? Avoids creating too many columns
```

#### Comparison Table:

| Method | When to Use | Pros | Cons | Example |
|--------|-------------|------|------|---------|
| **Label Encoding** | Ordinal categories (inherent order) | • Preserves order<br>• Single column<br>• Simple | • Creates false order for nominal<br>• Algorithms may misinterpret | Education: Bachelor=0, Master=1, PhD=2 |
| **One-Hot Encoding** | Nominal categories (no order), < 10 categories | • No false order<br>• Each category separate<br>• Works with all algorithms | • Creates many columns<br>• Can cause curse of dimensionality | Department: IT, HR, Finance → 3 columns |
| **Target Encoding** | Many categories (>10), nominal | • Keeps single column<br>• Captures target relationship | • Can overfit<br>• More complex | City with 50+ values |

---

### 🎯 Decision Framework for Train-Test Split | إطار القرار لتقسيم البيانات

**Key Question**: What split ratio should I use?

#### Decision Tree:

```
How much data do you have?
├─ < 1000 samples → Use 70/30 or 80/20
│   └─ Why? Need enough test data for reliable evaluation
│
├─ 1000-10,000 samples → Use 80/20
│   └─ Why? Standard split, good balance
│
└─ > 10,000 samples → Use 90/10 or 95/5
    └─ Why? Large datasets, can use less for testing
```

#### Comparison Table:

| Split Ratio | When to Use | Pros | Cons | Example |
|-------------|-------------|------|------|---------|
| **70/30** | Small datasets (< 1000) | • More test data<br>• Reliable evaluation | • Less training data | Dataset with 500 samples |
| **80/20** | Medium datasets (1000-10k) | • Standard split<br>• Good balance | • May need adjustment | Dataset with 5000 samples |
| **90/10** | Large datasets (> 10k) | • More training data<br>• Still enough test data | • Less test data | Dataset with 50,000 samples |

---

### 📊 Real-World Examples | أمثلة من العالم الحقيقي

#### Example 1: House Price Prediction
- **Features**: Size (1000-5000 sq ft), Age (0-50 years), Location (A, B, C)
- **Scaling Decision**: STANDARDIZATION (different scales, normal-ish distribution)
- **Encoding Decision**: ONE-HOT for Location (nominal, 3 categories)
- **Split Decision**: 80/20 (medium dataset)
- **Reasoning**: Size and age need scaling, location needs encoding, standard split

#### Example 2: Customer Segmentation
- **Features**: Income ($30k-$200k), Education (Bachelor, Master, PhD), Age (18-65)
- **Scaling Decision**: STANDARDIZATION (different scales)
- **Encoding Decision**: LABEL ENCODING for Education (ordinal: Bachelor < Master < PhD)
- **Split Decision**: 80/20
- **Reasoning**: Income needs scaling, education has order, standard split

#### Example 3: Image Classification
- **Features**: Pixel values (0-255), Category (10 classes)
- **Scaling Decision**: NORMALIZATION (need [0,1] for neural networks)
- **Encoding Decision**: ONE-HOT for Category (nominal, 10 classes)
- **Split Decision**: 80/20
- **Reasoning**: Pixels need [0,1] range, categories need one-hot, standard split

---

### ✅ Key Takeaways | النقاط الرئيسية

1. **Standardization for normal data** - Use when data is normally distributed
2. **Normalization for bounded values** - Use when you need [0,1] range
3. **Label encoding for ordinal** - Use when categories have inherent order
4. **One-hot for nominal** - Use when categories have no order
5. **80/20 is standard** - Use for most datasets (adjust for very small/large)
6. **Always scale before encoding** - Scale numeric features first, then encode categorical
7. **Test your choices** - Try different methods and compare results

---

### 🎓 Practice Decision-Making | ممارسة اتخاذ القرار

**Scenario**: You have a dataset with:
- Income: $20,000 - $150,000 (normally distributed)
- Education: High School, Bachelor, Master, PhD (ordinal)
- City: 15 different cities (nominal)
- 5,000 samples

**Your task**: Decide preprocessing methods for each feature!

**Answers**:
1. **Income**: STANDARDIZATION (normal distribution, different scale)
2. **Education**: LABEL ENCODING (ordinal: High School < Bachelor < Master < PhD)
3. **City**: ONE-HOT ENCODING (nominal, 15 categories is acceptable)
4. **Split**: 80/20 (medium dataset, standard split)

---

**Connection to Next Steps**: 
- 📓 **Example 4: Linear Regression** - Uses preprocessed data to build models
- 📓 **Example 5: Polynomial Regression** - Extends linear regression with preprocessed data
